01 dependancy to gf
DekodeInteraktiv/hogan-form pull request #4
Opened 2017-10-24 15:04 UTC by trinef

2017-10-24 15:48 UTC, stian-overasen requested changes

2017-10-24 15:48 UTC, soverasen commented on composer.json
> -    "dannyvanholten/acf-gravityforms-add-on": "^1.2"
Pakker fra wpackagist-plugin kan ikke brukes uten repo-info:
```json
"repositories":[
        {
            "type":"composer",
            "url":"https://wpackagist.org"
        }
    ],
```

2017-10-24 15:48 UTC, soverasen commented on composer.json
> -    "dannyvanholten/acf-gravityforms-add-on": "^1.2"
Mangler indent.

2017-10-24 15:48 UTC, soverasen commented on assets/template.php
>  			gravity_form( trim( $this->form ), false, false, false, '', true );
Hvorfor trim() på en integer?

2017-10-24 15:49 UTC, soverasen commented on assets/template.php
>  			gravity_form( trim( $this->form ), false, false, false, '', true );
Ser nå at den koden jeg har kommentert egentlig ikke er en del av denne pull requesten, men still.

2017-10-24 15:53 UTC, soverasen commented on composer.json
> -    "dannyvanholten/acf-gravityforms-add-on": "^1.2"
Husk å også kjøre `composer update` når det gjøres endringer i composer.json slik at composer.lock blir oppdatert riktig. Det står feks dannyvanholten fortsatt i lock-fila.

2017-10-25 06:38 UTC, trinef commented on assets/template.php
>  			gravity_form( trim( $this->form ), false, false, false, '', true );
Joda, ser du koden er det bare fint med kommentarer uansett. Her har jeg dratt over gravityforms funksjon som er i  bruk på kirkensbymisjon. Husker ikke hvorfor det måtte på en trim der, men det burde ikke være nødvendig. Jeg fjerner den, og gå heller tilbake om det oppstår feil.

2017-10-25 07:14 UTC, merged